# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='Create PBC_2D Equation', kernelModule='Eq2D_PBC', kernelFunction='PBC_Eq_2D', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgIcon(p='DialogBox', fileName='WIT.png')
RsgGroupBox(name='GroupBox_1', p='DialogBox', text='The author from WIT-MEES', layout='0')
RsgTextField(p='GroupBox_1', fieldType='String', ncols=12, labelText='Input the Model Name :', keyword='modelName', default='Model-1')
RsgGroupBox(name='GroupBox_2', p='DialogBox', text='Boundary Edge Select', layout='0')
RsgHorizontalFrame(name='HFrame_1', p='GroupBox_2', layout='0', pl=0, pr=300, pt=0, pb=0)
RsgPickButton(p='GroupBox_2', text='Select the Left Edge     :', keyword='Edge_L', prompt='Pick an entity', entitiesToPick='MDB_GEOMETRY|EDGES', numberToPick='MANY')
RsgPickButton(p='GroupBox_2', text='Select the Right Edge   :', keyword='Edge_R', prompt='Pick an entity', entitiesToPick='MDB_GEOMETRY|EDGES', numberToPick='MANY')
RsgPickButton(p='GroupBox_2', text='Select the Up Edge      :', keyword='Edge_U', prompt='Pick an entity', entitiesToPick='MDB_GEOMETRY|EDGES', numberToPick='MANY')
RsgPickButton(p='GroupBox_2', text='Select the Down Edge  :', keyword='Edge_D', prompt='Pick an entity', entitiesToPick='MDB_GEOMETRY|EDGES', numberToPick='MANY')
RsgLabel(p='DialogBox', text='Tip: The plugin will delete RP point and regenerate :', useBoldFont=True)
RsgLabel(p='DialogBox', text='The RP-1 displacement X control Ux,x ', useBoldFont=False)
RsgLabel(p='DialogBox', text='The RP-1 displacement Y control Uy,x ', useBoldFont=False)
RsgLabel(p='DialogBox', text='The RP-1 displacement Y control Uy,y ', useBoldFont=False)
RsgLabel(p='DialogBox', text='The RP-2 displacement X control Ux,y ', useBoldFont=False)
dialogBox.show()